In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("./data_as_download/train_cap2018.csv", sep=",",header=0)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27310 entries, 0 to 27309
Data columns (total 60 columns):
fulltext                 27310 non-null object
sentences                27310 non-null int64
words                    27310 non-null int64
letters.all              27310 non-null int64
syllables                27310 non-null int64
punct                    27310 non-null int64
avg.sentc.length         27310 non-null float64
avg.word.length          27310 non-null float64
avg.syll.word            27310 non-null float64
sntc.per.word            27310 non-null float64
TTR                      27310 non-null float64
ARI                      27310 non-null float64
Bormuth                  27310 non-null float64
Coleman.C1               27310 non-null int64
Coleman.C2               27310 non-null int64
Coleman.C3               27310 non-null int64
Coleman.C4               27310 non-null int64
Coleman.Liau             27310 non-null int64
Dale.Chall               27310 non-null float64


In [4]:
print(data.shape)
y = data["level1"].as_matrix()
print(y[1:5])
u, indices = np.unique(y, return_inverse=True)
print(indices.shape)
y = indices+1
y

(27310, 60)
['C2' 'C2' 'C2' 'C2']
(27310,)


array([6, 6, 6, ..., 1, 1, 1])

In [5]:
X = data.as_matrix(columns=data.columns[2:51])

from sklearn import preprocessing
X = preprocessing.scale(X)

In [6]:
print(X)
print(X.shape)
X.mean()

[[ 3.9219497   4.53008337  4.44762067 ... -0.66215229 -0.24465449
   0.60681256]
 [ 2.64990183  3.16408487  2.87151247 ... -0.32747942 -0.24465449
   0.71845411]
 [ 2.64990183  3.1367649   2.88810308 ...  0.67653918 -1.01914318
   1.65218342]
 ...
 [-1.19024266 -1.22350229 -1.19318763 ...  1.34588491 -1.27730608
   0.42412639]
 [-1.02223634 -0.98308656 -0.96091905 ...  1.01121204 -0.76098028
   0.05875405]
 [-0.75822641 -0.61699896 -0.71205986 ... -0.32747942  0.78799711
  -0.99676603]]
(27310, 49)


-1.4612376484742793e-17

In [7]:
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split
import time
import datetime as dt

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
param_C = 100
param_gamma = 0.0125
classifier = svm.SVC(probability=False,cache_size=2000,C=param_C,gamma=param_gamma)

In [9]:
start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))
classifier.fit(X_train, y_train)
end_time = dt.datetime.now() 
#print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))

Start learning at 2018-09-07 09:11:50.415175
Elapsed learning 0:00:20.808851


In [10]:
predicted = classifier.predict(X_test)
cm = metrics.confusion_matrix(y_test, 6*(predicted>0))
print("Confusion matrix:\n%s" % cm)

Confusion matrix:
[[   0    0    0    0    0 3735]
 [   0    0    0    0    0 2529]
 [   0    0    0    0    0 1809]
 [   0    0    0    0    0  763]
 [   0    0    0    0    0  164]
 [   0    0    0    0    0   13]]


In [11]:
cm = metrics.confusion_matrix(y_test, predicted)
print("Confusion matrix:\n%s" % cm)

Confusion matrix:
[[3308  322   85   18    2    0]
 [ 326 1952  226   22    3    0]
 [  53  232 1422   96    6    0]
 [  12   33  143  552   23    0]
 [   5    7   14   39   98    1]
 [   2    1    0    2    6    2]]


In [12]:
Cost_M =[[ 0, 1 ,    2  ,   3  ,  4   ,   6],
         [ 1, 0 ,    1  ,   4  ,   5  ,   8],
         [ 3, 2 ,    0  ,   3  ,   5  ,   8],
         [10, 7 ,    5  ,   0  ,   2  ,   7],
         [20,16 ,   12  ,   4  ,   0  ,   8],
         [44,38 ,   32  ,  19  ,  13  ,   0]]

In [25]:
c = 100*sum(sum(cm*Cost_M))/sum(sum(cm))
print("you score is %.2f"% c)

you score is 44.91
